version: 2.1

jobs:
  react-test:
    working_directory: ~/HackMerced-V/client
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      # - restore_cache: # special step to restore the dependency cache
      #     key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Setup React Dependencies
          command: yarn install
      # - save_cache: # special step to save the dependency cache
      #     key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ./node_modules
      - run: 
          name: react test
          command: yarn test
  node-test:
    working_directory: ~/HackMerced-V/server
    docker:
      - image: circleci/node:9
      - image: mongo:3.4.4
    steps:
      - checkout
      # - restore_cache: # special step to restore the dependency cache
      #     key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Setup Node Dependencies
          command: yarn install
      # - save_cache: # special step to save the dependency cache
      #     key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ./node_modules
      - run:
          name: node test
          command: yarn test

workflows:
  HackMerced:
    jobs:
      - node-test
      - react-test:
          requires:
            - node-test
          filters:
            branches:
              only: master