version: 2.1

orbs:
  react:
    jobs:
      test:
        working_directory: ~/HackMerced-V/client
        docker:
          - image: circleci/node:9
        steps:
          - checkout
          - restore_cache: # special step to restore the dependency cache
              key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          - run:
              name: Setup Dependencies
              command: yarn install
          - save_cache: # special step to save the dependency cache
              key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
              paths:
                - ./node_modules
          - run: 
              name: test
              command: yarn test
  node:
    jobs:
      test:
        working_directory: ~/HackMerced-V/server
        docker:
          - image: circleci/node:9
          - image: mongo:3.4.4
        steps:
          - checkout
          - restore_cache:
              key: dependency-cache-{{ checksum "package.json" }}
          - run:
              name: installation
              command: yarn install
          - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                - ./node_modules
          - run:
              name: test
              command: yarn test

workflows:
  React:
    jobs:
      - react/test
  Node:
    jobs:
      - node/test